Add README, Makefile; update deps
yada was pulling in an old version of aleph which in turn was pulling
in an old version of Netty (4.1.11), which had this issue

https://github.com/netty/netty/issues/6855
java.lang.ClassNotFoundException: jdk.internal.misc.Unsafe

That exception would appear when running the production Uberjar

Updating aleph to 0.4.6, we get netty 4.1.25 (issue was fixed in 4.1.12)